### ISSUE TITLE
Prevent cutting-off attacks in version 2.0

### ISSUE THREAD

**Issue by aead** [minio/sio#16]
## Cutting-off attack
Currently version 1.0 is vulnerable for a quite obvious attack:

Let's assume an encrypted sequence `S` consists of `n` packages and the encryption key `K` is unique. An adversary can modify the sequence by removing the last `k` packages of `S`. This cutting-off-attack is not detected during decryption if `n` (or the length of `S`) is not known because no package (esp. the last package) depends on `n` / the length of `S`.

Why is this attack not prevented in 1.0:

It was assumed that multipart-PUT operations (see S3 multipart) require support for extending a sequence of packages. The basic idea was:
<code>S<sub>part_1</sub> = E(K, part_1) with Config.SequenceNumber = 0</code>
<code>S<sub>part_2</sub> = E(K, part_2) with Config.SequenceNumber = |S<sub>part_1</sub>| / (32+L)|</code>
<code>S<sub>part_3</sub> = E(K, part_3) with Config.SequenceNumber = |S<sub>part_1</sub>| / (32+L) + |S<sub>part_2</sub>| / (32+L)|
</code>

However it is not required to build one valid sequence from `k` smaller sequences. 
Instead each sequence can be encrypted separately:
<code>S<sub>part_1</sub> = E(K<sub>part_1</sub>, part_1)</code>
<code>S<sub>part_2</sub> = E(K<sub>part_2</sub>, part_2)</code>
<code>S<sub>part_3</sub> = E(K<sub>part_3</sub>, part_3)</code>

## Proposal Version 1.1

Version 1.1 can prevent the attack by introducing a final flag:
```
header = version | cipher | payload_length | final_flag | random
         1 byte  | 1 byte |     2 byte     |   1 byte   | 11 byte
``` 

Encryption is defined as `C, T = E(K, P, N, AAD)` where: 
- <code>AAD = version | cipher | payload_length | L<sub>s</sub></code> (<code>L<sub>s</sub></code> is the current length of all payloads - <code>L<sub>s,0</sub> = 0, L<sub>s,1</sub> = payload_length, L<sub>s,2</sub> = 2*payload_length</code>)
- <code>N = (final_flag | random) ⊕ i</code> (`i` is the index of the package - `0` for the first package, `1` for the second package, a.s.o)

Adding the current length of the sequence to `AAD` makes exchanging of packages slightly harder (if an encryption key is reused).
Xoring the `11` byte random value with the 'sequence number' provides a slightly lower collision probability compared to the `sequence number | random` construction. 

**Version 1.1:**
`H = V | C | L | F | R | P/C | T`
<code>AAD = V | C | L | L<sub>s</sub></code>
`N = (F | R) ⊕ i`
`C , T = E(K, P, N, AAD)`
`P, T = D(K, C, N, AAD)`

## SIV
I also thought about using a deterministic synthetic-IV scheme to provide integrity and confidentially even if an encryption key is reused. For example using a PRF to derive an unique encryption key per package from the encryption key (which would than be a master key) and the payload plaintext.
This was discarded because of:
 - Even if a fast PRF is used (SipHash / HighwayHash) the en/decryption speed decreases (2 passes over the data)
 - For every package a new AEAD cipher instance must be created (performance)
 - The header will be increase (from 16 to ~32 bytes) - This would require a major version update.

However, a SIV scheme should be taken into account for a major version update.

**Comment by harshavardhana** [comment]
> Can somebody comment on where things stand, format wise, between v1, v1.1 and v2? It's clear v1.1 fixes a critical issue, but it is rather unclear what V2 is. In any case, good work!

v1.1 was renamed to v2.0 @hemancuso

**Comment by hbakhtiyor** [comment]
@harshavardhana https://github.com/minio/sio/blob/master/DARE.md
where's the specification of version 2? the doc only for v1

**Comment by harshavardhana** [comment]
@hbakhtiyor https://github.com/minio/sio/pull/28 is a pending PR which should be merged.
