### ISSUE TITLE
[proposal]: export DARE overhead computation

### ISSUE THREAD

**Issue by aead** [minio/sio#22]
This is a proposal to simplify client code. Currently a client must compute the overhead DARE himself.
Since this is a relative common operation - eg. preallocate buffers - it should be part of the exported API.

The exported function could look like: `func Overhead(size uint64) uint64`
This function would work only correct (in all scenarios) for DARE 2.0. However since DARE 1.0 is considered as deprecated this may be fine and we can mention this explicitly in the doc of `Overhead`.

All other options ( I can see ) lead to an (IMO unnecessary) complexer API and don't provide much benefit. The strongest argument for adding this functionality also for DARE 1.0 is to provide a consistent API. However I think it is okay for us to make this cut here since the mistake of making payload size configurable (which is also marked as deprecated) should not influence future API decision.

**Comment by harshavardhana** [comment]
why not have an io.Reader, to provide a Size() as the function?

**Comment by aead** [comment]
Either we have to export an type/interface like: SizedReader (interface) or Reader (type). But this would break API comparability. If we just add the function to the reader users have to reflect on the reader...
