### ISSUE TITLE
Export errors

### ISSUE THREAD

**Issue by ShoshinNikita** [minio/sio#29]
It would be useful to have opportunity to compare errors in some cases . For example,
```go
_, err = sio.Decrypt(w, f, sio.Config{Key: key})
if err != nil {
	if err == sio.ErrUnsupportedVersion {
		os.Copy(w, f) // file wasn't encrypted
	} else {
		log.Println(err)
	}
}
```

**Comment by aead** [comment]
@ShoshinNikita 
`if err == sio.ErrUnsupportedVersion` is actually no evidence that the file/stream is not encrypted.
It may be the case - for example if you've encrypted and non-encrypted data and you're **sure** that the file was not maliciously modified. But then you you should actually save some additional information about the file clearly distinguishing encrypted and non-encrypted files.

Further you can already detect whether the decryption fails (for multiple reasons - usually integrity verification failures):
```
_, err = sio.Decrypt(w, f, sio.Config{Key: key})
if err != nil {
        if _, ok := err.(sio.Error); ok {
		// integrity verification failed.
	} else {
               // some other error (probably IO)
        }
}
```
alternatively:
```
_, err = sio.Decrypt(w, f, sio.Config{Key: key})
if err != nil {
        switch err.(type) {
	case sio.Error:
		// integrity verification failed.
	default:
		// some other error (probably IO)
	}
}
```

**Comment by kannappanr** [comment]
@ShoshinNikita Closing this issue based on the comment by @aead . Please feel free to reach out to us, if you have further questions.
