### ISSUE TITLE
Webserver implementation

### ISSUE THREAD

**Issue by MicuAlexandru** [minio/sio#44]
Hi, 

  I don't know exactly where I can send this question and I figured this is an ok place for it. I heard of encrypt-at-rest a wile ago and now, I want to make a project for my university where a client sends data to a database from a php webserver and that data is encrypted with this DEAR but I have not found any kind of descriptions or steps to do that. 

  I was wandering if anybody knows a wiki for this kind of setup or if you can explain a bit how this setup should work. 

I thank you very much for this lib and I waiting for your reply! 
Alexandru

**Comment by harshavardhana** [comment]
@MicuAlexandru this is a Go library, you need to write PHP equivalent of this if you want server side implementation. If not you can have a client that encrypts using this library and sends it to your PHP Server.

Implementing this is out of our scope, you would have to learn this yourself.
